<a href="https://colab.research.google.com/github/a33211/Data-science-homeworks/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Homework 1**

---



In [1]:
import random
import numpy as np




def randomize (start, finish):
  return random.randint(start, finish)

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

---



In [ ]:
task_1 = np.arange(10)
print(task_1)

[0 1 2 3 4 5 6 7 8 9]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та 
виведіть його значення.

---



In [ ]:
task_2 = np.zeros(shape = (3,3))
print(task_2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
task_3 = np.random.randint(1,10, (5, 5))
print(task_3)

[[4 8 8 7 0]
 [6 3 5 2 0]
 [0 0 4 7 5]
 [0 0 3 1 1]
 [0 4 5 6 7]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
task_4 = np.random.rand(4, 4)
print(task_4)

[[1.46394767e-01 9.41369398e-01 8.53313726e-01 5.53950427e-01]
 [7.81724234e-01 4.35071915e-01 7.56859154e-01 9.00279509e-04]
 [9.47580850e-01 2.38073439e-01 6.59515881e-01 9.81348074e-01]
 [1.77893498e-01 1.38522041e-01 4.55702991e-01 8.06951881e-01]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
task_5_arr_1 = np.random.randint(1,10,(1,5))
task_5_arr_2 = np.random.randint(1,10,(1,5))
sum_task_5 = task_5_arr_1 + task_5_arr_2
div_task_5 = task_5_arr_1 - task_5_arr_2
mult_task_5 = task_5_arr_1 * task_5_arr_1
print(sum_task_5, div_task_5, mult_task_5)

[[11  6  6 10 12]] [[-3 -2 -4 -4 -4]] [[16  4  1  9 16]]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
task_6_arr_1 = np.random.rand(1,7)
task_6_arr_2 = np.random.rand(1,7)
mult_task_6 = task_6_arr_1*task_6_arr_2
print(mult_task_6)

[[0.07791426 0.08814972 0.97032477 0.56738812 0.03443431 0.22014044
  0.25067897]]


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою

In [ ]:
task_7_arr_1 = np.random.randint(1,10,(2,2))
task_7_arr_2 = np.random.randint(1,10,(2,3))
random_matrix = [[random.randint(1,10) for e in range(2)] for e in range(3)]
mult_task_7 = np.dot(task_7_arr_1,task_7_arr_2)
# print(type(random_matrix))
# print(type(task_7_arr_2))
print(mult_task_7)

<class 'list'>
<class 'numpy.ndarray'>


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
task_8_arr_straight = np.random.randint(1,10,(3,3))
task_8_arr_inverted = np.linalg.inv(task_8_arr_straight)
print(task_8_arr_straight)
print(task_8_arr_inverted)

[[7 6 1]
 [3 6 8]
 [1 6 7]]
[[ 0.05555556  0.33333333 -0.38888889]
 [ 0.12037037 -0.44444444  0.49074074]
 [-0.11111111  0.33333333 -0.22222222]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [ ]:
task9_arr = np.random.rand(4,4)
print(task9_arr)
task9_arr_transponed = task9_arr.T
print(task9_arr_transponed)

[[0.16583858 0.68481974 0.40137802 0.54188226]
 [0.15467139 0.47308628 0.20960346 0.7261212 ]
 [0.22209458 0.07903434 0.76067916 0.38309156]
 [0.38224667 0.79176799 0.46256322 0.64565594]]
[[0.16583858 0.15467139 0.22209458 0.38224667]
 [0.68481974 0.47308628 0.07903434 0.79176799]
 [0.40137802 0.20960346 0.76067916 0.46256322]
 [0.54188226 0.7261212  0.38309156 0.64565594]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [ ]:
task10_arr = np.random.randint(1, 10,(3,4))
task_10_vector = np.random.randint(1,10,(1,4))
task_10_multiply = task_10_vector.dot(task10_arr.T)
print(task10_arr, task_10_vector)
print(task_10_multiply)

[[5 7 1 6]
 [8 8 4 8]
 [9 2 6 3]] [[5 3 5 2]]
[[ 63 100  87]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [ ]:
task11_arr = np.random.rand(2,3)
task_11_vector = np.random.rand(1,3)
task_11_multiply = task_11_vector.dot(task11_arr.T)
print (task_11_multiply)

[[0.62662415 1.19374716]]


12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [ ]:
task12_arr_1 = np.random.randint(1, 10,(2,2))
task12_arr_2 = np.random.randint(1, 10,(2,2))
task12_mult = np.multiply(task12_arr_1, task12_arr_2)
print(task12_arr_1, task12_arr_2)
print(task12_mult)

[[3 3]
 [4 7]] [[7 1]
 [7 5]]
[[21  3]
 [28 35]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [ ]:
task13_arr_1 = np.random.randint(1, 10,(2,2))
task13_arr_2 = np.random.randint(1, 10,(2,2))
test1 = np.matmul(task13_arr_1, task13_arr_2)
print(type(test1), test1)
test2 = np.dot(task13_arr_1, task13_arr_2)
print(type(test2), test2)
print(test1 == test1)

<class 'numpy.ndarray'> [[109  72]
 [ 88  72]]
<class 'numpy.ndarray'> [[109  72]
 [ 88  72]]
[[ True  True]
 [ True  True]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [ ]:
task14_arr = np.random.randint(1, 100,(5,5))
task14_arr_sum = task14_arr.sum()
print(task14_arr_sum)

1170


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [ ]:
task15_arr_1 = np.random.randint(1, 10,(4,4))
task15_arr_2 = np.random.randint(1, 10,(4,4))
task15_arr_div = task15_arr_1-task15_arr_2
print(task15_arr_1)
print("_____________________")
print(task15_arr_2)
print("_____________________")
print(task15_arr_div)

[[6 3 4 6]
 [8 8 5 7]
 [4 7 5 9]
 [4 4 6 6]]
_____________________
[[8 3 4 8]
 [7 9 2 4]
 [3 3 1 3]
 [9 8 2 4]]
_____________________
[[-2  0  0 -2]
 [ 1 -1  3  3]
 [ 1  4  4  6]
 [-5 -4  4  2]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [ ]:
task16_arr = np.random.randint(1, 10,(3,3))
task16_arr_sum = task16_arr.sum(axis = 0)
print(task16_arr_sum)

[20 15 20]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [3]:
from numpy.linalg import matrix_power

task16_arr = np.random.randint(2, 10, (3,4))
print(task16_arr)
task16_arr_empowered = np.power(task16_arr, 2)
print(task16_arr_empowered)

[[5 2 8 4]
 [9 4 6 7]
 [3 4 8 2]]
[[25  4 64 16]
 [81 16 36 49]
 [ 9 16 64  4]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [ ]:
task18_arr = np.random.randint(1, 50,(1,4))
print(task18_arr)
task18_arr_sqrt = np.sqrt(task18_arr)
print(task18_arr_sqrt)

[[41 16 10 35]]
[[6.40312424 4.         3.16227766 5.91607978]]
